### ISSUE TITLE
Countix-AV and Extreme Countix-AV dataset

### ISSUE THREAD

**Issue by cshanjiewu** [xiaobai1217/RepetitionCounting#1]
Hi, thank you for sharing this wonderful work. I've been working on audio-related repetitive tasks recently too. Can I ask when you can release the CSV files of Countix-AV and Extreme Countix-AV that you mentioned in your paper?

**Comment by xiaobai1217** [comment]
> Hi, thank you for sharing this wonderful work. I've been working on audio-related repetitive tasks recently too. Can I ask when you can release the CSV files of Countix-AV and Extreme Countix-AV that you mentioned in your paper?

Hi, I will release the files by the end of this week!

**Comment by cshanjiewu** [comment]
OK, thank you for your reply.
