### ISSUE TITLE
Extracted audio files to train model

### ISSUE THREAD

**Issue by abner742** [xiaobai1217/RepetitionCounting#10]
Hello, I hope to get your extracted audio files (data_loader2.py) and vggsound_avgpool.pth.tar to train the audio counting model (train_audio.py).
Thanks!
This is my email: 3071706018@qq.com

**Comment by xiaobai1217** [comment]
Hi, 
The vggsound_avgpool.pth.tar can be downloaded at http://www.robots.ox.ac.uk/~vgg/data/vggsound/models/H.pth.tar
You can extract the audio files yourself by
import moviepy.editor as mp
clip = mp.VideoFileClip('*.mp4').subclip(start_time, end_time)
clip.audio.write_audiofile(path_for_save)

**Comment by abner742** [comment]
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaobai1217/RepetitionCounting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月12日(星期天) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaobai1217/RepetitionCounting] Extracted audio files to train model (Issue #10)





 
Hi,
 The vggsound_avgpool.pth.tar can be downloaded at http://www.robots.ox.ac.uk/~vgg/data/vggsound/models/H.pth.tar
 You can extract the audio files yourself by
 import moviepy.editor as mp
 clip = mp.VideoFileClip('*.mp4').subclip(start_time, end_time)
 clip.audio.write_audiofile(path_for_save)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
