### ISSUE TITLE
Where can I download countix_ Train_ Examples_ Clean CSV

### ISSUE THREAD

**Issue by Tara-Liu** [xiaobai1217/RepetitionCounting#14]
There is no such part in the dataset. Where can I download countix_ Train_ Examples_ Clean CSV?

**Comment by xiaobai1217** [comment]
Hi, we tried to download all the videos provided officially at https://sites.google.com/view/repnet However, many videos on Youtube are not available any more so in countix_Train_examples_clean.csv, we just keep the videos that we successfully downloaded

**Comment by Tara-Liu** [comment]
> 
Do I need to generate this CSV file myself? I don't seem to have found its download address

**Comment by Tara-Liu** [comment]
Do I need to generate this CSV file myself? I don't seem to have found its download address

**Comment by xiaobai1217** [comment]
You can download the dataset by this link provided by RepNet https://storage.googleapis.com/deepmind-media/Datasets/countix.tar.gz then you need to download the videos, after that you just need to delete the lines that you cannot download the videos

**Comment by Tara-Liu** [comment]
I know you can download videos through the link you provided, but you did not provide countix_ train_ examples_ clean.CSV, which makes the data in the training phase unable to be loaded

**Comment by xiaobai1217** [comment]
You need to generate the file yourself, according to your own video clips from the downloaded videos.

**Comment by Tara-Liu** [comment]
OK, thanks for your answer.
