### ISSUE TITLE
What's the meaning of 34 in train.py?

### ISSUE THREAD

**Issue by abcdvzz** [xiaobai1217/RepetitionCounting#15]
The code says you use 34*41 as the dimension of the output layer. Why do you use 34? What's the meaning of it? I assume 41 means the number of classes but why 41 instead of 43?

**Comment by Sid2697** [comment]
Hello @abcdvzz,

Did you figure out the reason for this? According to the paper, the dimensions of both the fully connected layers should be the same (41 or 43 in this case). @xiaobai1217  Can you please share your thoughts on this? Thanks!
