### ISSUE TITLE
Can't reproduce similar results as described in the paper！

### ISSUE THREAD

**Issue by guoxigan** [xiaobai1217/RepetitionCounting#17]
I tested the model on UCFRep and countix with the checkpoint released by the author, and got  lower results. The test results of visual model on UCFRep are 0.604(MAE) and 0.447(OBO)， which far lower than 0.143(MAE) and 0.800(OBO).

**Comment by xiaobai1217** [comment]
Hi, you are using the checkpoint trained on Countix for the UCFRep, so surely it cannot reproduce the results. The model certainly should be re-trained on UCFRep.

**Comment by guoxigan** [comment]
Thanks for your quick reply!  I'll try it again.
