### ISSUE TITLE
Low result in Countix

### ISSUE THREAD

**Issue by guoxigan** [xiaobai1217/RepetitionCounting#18]
Hello, I collected Countix from Youtube(maybe a little different from yours), and I test visual model on Countix test set with the checkpoint released by the author. I got the result of OBO(0.4973) and MAE(0.4605). The OBO is very good, but the MAE is far from the results in the paper(MAE:0.314). What is the possible reason for this?   Thanks!

**Comment by xiaobai1217** [comment]
Fewer videos on Countix are available on Youtube now. When I did the experiments three years ago, there were already some videos that were not available any more. So your dataset is absolutely different from mine.

**Comment by DWhettam** [comment]
@guoxigan are you able to share your testing code? I am currently a long way off reproducing the results on the provided checkpoints. Thanks!
