### ISSUE TITLE
countix dataset

### ISSUE THREAD

**Issue by StarkYYy** [xiaobai1217/RepetitionCounting#4]
Could you please release a compressed file containing all the videos for each dataset？(Google network disk or baidu network disk). Thank you very much!! It would be better if the training code could be released as soon as possible :)

**Comment by xiaobai1217** [comment]
Hi, the Extreme Countix-AV has already been released. I will check whether the file size will allow me to release the pre-extracted Countix-AV, and the training code will be released this month.

**Comment by xiaobai1217** [comment]
Anyway I think you can download the videos easily by the csv file of Countix-AV we provided, using the following commands in python: 

import youtube_dl
       url = 'https://www.youtube.com/watch?v=' + youtube_id

       cmd = ['youtube-dl', '--user-agent', '""', '--ignore-errors', '-o', save_path, '"{}"'.format(url)]
       os.system(' '.join(cmd))

**Comment by xiaobai1217** [comment]
The training code has been released.
