### ISSUE TITLE
Unsure how to generate the *.npy files needed for the generate_csv4sr.py script

### ISSUE THREAD

**Issue by ethandrzb** [xiaobai1217/RepetitionCounting#5]
I am attempting to recreate your results for a research project and have finished training the visual model.

The README.md file says I need to perform an intermediate step (shown below) before running the generate_csv4sr.py script to train the temporal stride decision models.

> **Then, generate the counting predictions with the model of the sample rate from 1 to 7**. After that, run this script to get the csv file for training the temporal stride decision module:

Were these predictions generated/stored during training, or am I missing something?

**Comment by xiaobai1217** [comment]
Yes, I forgot to include one script "eval_all_sr.py", which has been newly uploaded. Pls run this script first with the visual model to get the counting prediction with respect to each sample rate for each video. Then generate the csv file for training the temporal stride decision module.
