### ISSUE TITLE
countix_train_examples_clean.csv

### ISSUE THREAD

**Issue by StarkYYy** [xiaobai1217/RepetitionCounting#6]
Missing "countix_train_examples_clean.csv". It appears that "countix_train_examples_clean.csv" has an "sample rate" column more than "countix_train.csv".

**Comment by xiaobai1217** [comment]
We generated the "countix_train_examples_clean.csv" file when we cropped the original youtube videos into clips, just record ed the time points of the clips and the groundtruths. The "sample rate" column was for our ablation study, it is not used during training. I have deleted it in the new dataloader code. You can replace this part of the code with your own one.
