### ISSUE TITLE
name 'tensor' is not defined 

### ISSUE THREAD

**Issue by GeLee-Q** [xiaobai1217/RepetitionCounting#7]
> Traceback (most recent call last):
  File "run_demo.py", line 87, in <module>
    outputs = get_visual_count(video1, sample_rate, model)
  File "util.py", line 136, in get_visual_count
    outputs2 = torch.sum(outputs2 * tensor, dim=1, keepdim=True)
NameError: name 'tensor' is not defined

I have installed the required dependent libraries，but after I run the demo code , it shows the error above.
and I check the ''util.py'' , I do not find the "tensor" which you should defined it at the'' def get_visual_count()''
`def get_visual_count(video1, sample_rate, model, visual_branch_num=41)`

**Comment by xiaobai1217** [comment]
Thanks for checking. 
This can be fixed by https://github.com/xiaobai1217/RepetitionCounting/issues/2#issuecomment-854068432 
I have updated the code.
