### ISSUE TITLE
Joint 4 module for training

### ISSUE THREAD

**Issue by xuwanyan1998** [xiaobai1217/RepetitionCounting#9]
Thanks for share your great work!
And I have a little problem about whether you train your 4 module together at last, or just train them separately in different dataset, and then joint them one by one for the last inference.

**Comment by xiaobai1217** [comment]
Hi, thank you! 
The modules are trained separately on the same dataset and we use all of them during inference.

**Comment by xuwanyan1998** [comment]
> Hi, thank you! The modules are trained separately on the same dataset and we use all of them during inference.

And are the sight and sound module trained firstly, and using the 2 module to train the other 2 module?

**Comment by xiaobai1217** [comment]
Yes!
